### ISSUE TITLE
Running calfjackhost in "headless" (no GUI) mode

### ISSUE THREAD

**Issue by haasn** [calf-studio-gear/calf#184]
It would be useful to be able to run calfjackhost without requiring the use of a GUI, for when you want to load an existing filter preset (`.xml`) from e.g. LADISH.

Right now, my preferred work-around is to use carla (which has a `--no-gui` option) for this job, but since 1. the calfjackhost .xml format is incompatible with the `.carxp` format and 2. the carla GUI doesn't seem to support calf plugins too well, I always have to go back to calfjackhost to change parameters and then manually copy these over to the `.carxp` file.

In terms of preferred solutions I'd rank:

1. The ability to run calfjackhost without the use of an X server / headless
2. The ability to import/export to .carxp format in calfjackhost
3. The existence of a tool for automatic conversion between the calfjackhost .xml and .carxp.

I'll eventually get around to writing a program for 3., but obviously solutions 1 and 2 would be preferred.

**Comment by haasn** [comment]
Turns out there's an even simpler solution: building carla with gtk2 support allows me to use the calf GUIs even in carla, which I guess means I no longer need calfjackhost at all. I'll let you decide what to do with this issue, since it's still (IMO) a valid feature request.

**Comment by trebmuh** [comment]
A **--no-gui** option could be great for calfjackhost
:+1: on this

**Comment by haasn** [comment]
Really cool, thanks for that!

**Comment by Bleuzen** [comment]
@boomshop  Is it still possible to open the gui when starting with this new option?
I would like to have a gui to tweak effects during they are in use, but the window should start hidden / in tray.

**Comment by haasn** [comment]
Incidentally, I'd also like to point out that the `--no-gui` mode still does not work when actually running headless (i.e. no X server), since even in `--no-gui` mode it tries initializing Gtk which fails if `DISPLAY` is unset.

Ideally calfjackhost should detect if Gtk fails to open the display and instead continue running (in GUI-less mode).

**Comment by boomshop** [comment]
Oops sorry, my fault, overlooked initialization and start of the main loop. Should be fixed in master now.

**Comment by jimzrt** [comment]
I think the issue is not fully resolved yet.
When starting with --no-gui option on latest master I get "Gtk-WARNING .. cannot open display:" on my headless server.
I think the problem is the constructor of host_session.
has_gui is set by default to true and a window is initialized: [host_session.cpp#L44](https://github.com/calf-studio-gear/calf/blob/6c0610bf81060432e69b942b56bf5160f3d91b05/src/host_session.cpp#L44).
I don't know how you want to pass the no_gui parameter, because command line parameters are parsed after host_session is initialized, otherwise I would have made a pull request.
Also, I think "has_trayicon" should additionally be set to false when choosing the no_gui mode.

**Comment by haasn** [comment]
Indeed, it still needs DISPLAY set. It also hangs forever on exit. (Not sure exactly what "exit" means, but it hangs if I try stopping the filter in claudia)

**Comment by boomshop** [comment]
I just merged jimzrt's pull request. Please test if things are fixed and report back if possible. Thanks in advance.

**Comment by haasn** [comment]
It now starts successfully without `DISPLAY` being set. However, it still hangs forever when I try disabling the filter in `claudia` again. (This only happens in no-gui mode)

That might be a separate issue though.

**Comment by jimzrt** [comment]
I made a new pull request that addresses this issue (#222)
@haasn can you try this version to see if it fixes the problem?

**Comment by haasn** [comment]
Works now. Thanks for the continued efforts!
